const express=require('express');const fs=require('fs');const path=require('path');const crypto=require('crypto');
const app=express();app.use(express.json());app.use(express.static(__dirname));
async function tg(chat,text){if(!process.env.BOT_TOKEN||!chat)return;try{await fetch(`https://api.telegram.org/bot${process.env.BOT_TOKEN}/sendMessage`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({chat_id:chat,text})});}catch(e){console.error('Telegram:',e.message)}}
const file=path.join(__dirname,'data.json');let db=fs.existsSync(file)?JSON.parse(fs.readFileSync(file)): {products:[],codes:[],orders:[],promocodes:[]};
const save=()=>fs.writeFileSync(file,JSON.stringify(db,null,2));
function user(req){return req.headers['x-telegram-id']||'demo';}
function admin(req,res,next){if(process.env.ADMIN_TOKEN&&req.headers.authorization!==`Bearer ${process.env.ADMIN_TOKEN}`)return res.status(401).json({error:'Unauthorized'});next();}
app.get('/api/products',(req,res)=>{let q=(req.query.q||'').toLowerCase();res.json(db.products.filter(p=>(!q||p.name.toLowerCase().includes(q)||(p.category||'').toLowerCase().includes(q))).map(p=>({...p,available:(Number.isFinite(p.stock)?p.stock:db.codes.filter(c=>c.productId===p.id&&c.status==='free').length),soldOut:(Number.isFinite(p.stock)?p.stock:db.codes.filter(c=>c.productId===p.id&&c.status==='free').length)<=0||p.status==='disabled'})));});
app.get('/api/products/:id',(req,res)=>{let p=db.products.find(x=>x.id===req.params.id);if(!p)return res.sendStatus(404);res.json({...p,available:(Number.isFinite(p.stock)?p.stock:db.codes.filter(c=>c.productId===p.id&&c.status==='free').length),soldOut:(Number.isFinite(p.stock)?p.stock:db.codes.filter(c=>c.productId===p.id&&c.status==='free').length)<=0||p.status==='disabled'});});
app.post('/api/orders',(req,res)=>{let p=db.products.find(x=>x.id===req.body.productId)||db.products.find(x=>x.name===req.body.name);if(!p){p={id:'p_'+Date.now(),name:req.body.name||'Товар',price:Number(req.body.amount)||0,status:'available'};db.products.push(p);}let id='ORD-'+Date.now();let o={id,userId:user(req),productId:p.id,amount:req.body.amount||p.price,status:'pending',createdAt:new Date().toISOString(),paymentUrl:'/api/payments/'+id};db.orders.push(o);save();res.status(201).json(o);});
app.get('/api/payments/:id',(req,res)=>{let o=db.orders.find(x=>x.id===req.params.id);if(!o)return res.sendStatus(404);res.sendFile(path.join(__dirname,'payment.html'));});
app.post('/api/payments/:id/demo',(req,res)=>{let o=db.orders.find(x=>x.id===req.params.id);if(!o)return res.sendStatus(404);req.url='/api/payments/'+req.params.id+'/webhook';return app._router.handle(req,res,()=>{});});
app.post('/api/payments/:id/webhook',async(req,res)=>{let o=db.orders.find(x=>x.id===req.params.id);if(!o)return res.sendStatus(404);if(o.status==='delivered')return res.json(o);let c=db.codes.find(x=>x.productId===o.productId&&x.status==='free');if(!c){let code='PLT-'+crypto.randomBytes(10).toString('hex').toUpperCase();while(db.codes.some(x=>x.code===code))code='PLT-'+crypto.randomBytes(10).toString('hex').toUpperCase();c={id:'c_'+Date.now(),productId:o.productId,code,status:'used'};db.codes.push(c);}else c.status='used';o.status='delivered';c.orderId=o.id;o.code=c.code;o.paidAt=new Date().toISOString();o.deliveredAt=new Date().toISOString();save();await tg(o.userId,`✅ Оплата подтверждена\nЗаказ: ${o.id}\nВаш код: ${o.code}`);await tg(process.env.ADMIN_TELEGRAM_ID,`🛒 Новый заказ ${o.id}\nСумма: ${o.amount} ₽\nКод выдан: ${o.code}`);res.json(o);});
app.get('/api/orders',(req,res)=>res.json(db.orders.filter(o=>o.userId===user(req))));
app.get('/api/admin/products',admin,(req,res)=>res.json(db.products.map(p=>({...p,available:(Number.isFinite(p.stock)?p.stock:db.codes.filter(c=>c.productId===p.id&&c.status==='free').length),soldOut:(Number.isFinite(p.stock)?p.stock:db.codes.filter(c=>c.productId===p.id&&c.status==='free').length)<=0||p.status==='disabled'}))));
app.get('/api/admin/orders',admin,(req,res)=>res.json(db.orders));
app.patch('/api/admin/orders/:id',admin,(req,res)=>{let o=db.orders.find(x=>x.id===req.params.id);if(!o)return res.sendStatus(404);if(req.body.status)o.status=req.body.status;save();res.json(o);});
app.patch('/api/admin/products/:id',admin,(req,res)=>{let p=db.products.find(x=>x.id===req.params.id);if(!p)return res.sendStatus(404);Object.assign(p,req.body);save();res.json(p);});
app.get('/api/admin/codes',admin,(req,res)=>res.json(db.codes.map(c=>({...c,code: c.code}))));
app.post('/api/admin/products',admin,(req,res)=>{let p={id:req.body.id||'p_'+Date.now(),name:req.body.name,description:req.body.description||'',category:req.body.category||'',price:Number(req.body.price)||0,currency:req.body.currency||'RUB',status:req.body.status||'available',image:req.body.image||'',createdAt:new Date().toISOString()};db.products.push(p);save();res.status(201).json(p);});
app.post('/api/admin/codes',admin,(req,res)=>{let items=Array.isArray(req.body.codes)?req.body.codes:[];let added=0;for(const code of items){if(!code||db.codes.some(c=>c.code===code))continue;db.codes.push({id:'c_'+Date.now()+'_'+added,productId:req.body.productId,code,status:'free',createdAt:new Date().toISOString()});added++;}save();res.json({added});});
app.post('/api/admin/stock',admin,(req,res)=>{let n=Math.max(0,Number(req.body.quantity)||0),added=0;for(let i=0;i<n;i++){let code='PLT-'+crypto.randomBytes(8).toString('hex').toUpperCase();db.codes.push({id:'c_'+Date.now()+'_'+i,productId:req.body.productId,code,status:'free',createdAt:new Date().toISOString()});added++;}save();res.json({added});});
app.listen(process.env.PORT||3000,()=>console.log('Platas API ready'));

